// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pb/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message สำหรับรับส่งข้อมูล
type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_pb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_pb_service_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	FromService   string                 `protobuf:"bytes,2,opt,name=from_service,json=fromService,proto3" json:"from_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_pb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DataResponse) GetFromService() string {
	if x != nil {
		return x.FromService
	}
	return ""
}

var File_pb_service_proto protoreflect.FileDescriptor

const file_pb_service_proto_rawDesc = "" +
	"\n" +
	"\x10pb/service.proto\x12\x02pb\"\x1d\n" +
	"\vDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\fDataResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12!\n" +
	"\ffrom_service\x18\x02 \x01(\tR\vfromService2=\n" +
	"\rDomainService\x12,\n" +
	"\aGetData\x12\x0f.pb.DataRequest\x1a\x10.pb.DataResponse2G\n" +
	"\x13OrchestratorService\x120\n" +
	"\vProcessData\x12\x0f.pb.DataRequest\x1a\x10.pb.DataResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_service_proto_rawDescOnce sync.Once
	file_pb_service_proto_rawDescData []byte
)

func file_pb_service_proto_rawDescGZIP() []byte {
	file_pb_service_proto_rawDescOnce.Do(func() {
		file_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_service_proto_rawDesc), len(file_pb_service_proto_rawDesc)))
	})
	return file_pb_service_proto_rawDescData
}

var file_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_service_proto_goTypes = []any{
	(*DataRequest)(nil),  // 0: pb.DataRequest
	(*DataResponse)(nil), // 1: pb.DataResponse
}
var file_pb_service_proto_depIdxs = []int32{
	0, // 0: pb.DomainService.GetData:input_type -> pb.DataRequest
	0, // 1: pb.OrchestratorService.ProcessData:input_type -> pb.DataRequest
	1, // 2: pb.DomainService.GetData:output_type -> pb.DataResponse
	1, // 3: pb.OrchestratorService.ProcessData:output_type -> pb.DataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_service_proto_init() }
func file_pb_service_proto_init() {
	if File_pb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_service_proto_rawDesc), len(file_pb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_service_proto_goTypes,
		DependencyIndexes: file_pb_service_proto_depIdxs,
		MessageInfos:      file_pb_service_proto_msgTypes,
	}.Build()
	File_pb_service_proto = out.File
	file_pb_service_proto_goTypes = nil
	file_pb_service_proto_depIdxs = nil
}
